name: spotify_qr_app
description: "Spotify QR Code Scanner App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^3.0.0
  spotify_sdk: ^3.0.2
  http: ^1.2.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
